# Data paths
output_path: !!str "/gpfs/projects/acad/sail/GenCast/data/filtering/2019_03/idealist/"
data_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/trajectories/2019_03_29_1.0_13_30.nc"

# Checkpoint path
checkpoint_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/checkpoints/gencast_1deg.npz"

# Filter parameters
num_samples: !!int 256
N_threshold_min: !!int 50
N_threshold_max: !!int 60
alpha_init: !!float 1e-6
max_iter_alpha: !!int 100

# Mask (observations)
mask_sat_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/grid_4x4.npy"
mask_ws_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/grid_4x4.npy"

# Observed variables (observations)
observed_variables_sat:
  - "temperature"
observed_variables_ws:
  - "2m_temperature"

# Covariance matrix of unnormalized observations
sigma_y_sat_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/covariance/satellite_idealist.npy"
sigma_y_ws_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/covariance/weather_stations_idealist.npy"

# Sampler
sampler: "abs"
sampler_config:
  max_noise_level: !!float 88.0
  min_noise_level: !!float 2e-5
  num_noise_levels: !!int 32
  rho: !!float 6.0
  order: !!int 3
  correction: !!bool True
  num_correction_steps: !!int 2
  delta: !!float 0.25

# Stats path
min_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/min_x.nc"
std_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/std_x.nc"
std_z_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/std_z.nc"
mean_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/mean_x.nc"

# MMPS Solver
solver: !!str "bicgstab"
max_iter: !!int 3
tol: !!float 1e-10