# Number of samples to generate
num_samples: !!int 512

# Data paths
conditional_output_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/PPC/all_variables/"
unconditional_output_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/PPC/unconditional/"
data_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/trajectories/2019_03_29_1.0_13_30.nc"

# Checkpoint path
checkpoint_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/checkpoints/gencast_1deg.npz"

# Stats path
min_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/min_x.nc"
std_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/std_x.nc"
std_z_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/std_z.nc"
mean_x_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/stats/mean_x.nc"

# Sampler
sampler: "abs"
sampler_config:
  max_noise_level: !!float 88.0
  min_noise_level: !!float 1e-5
  num_noise_levels: !!int 32
  rho: !!float 6.0
  order: !!int 3
  correction: !!bool True
  num_correction_steps: !!int 2
  delta: !!float 0.25

# Mask (observations)
mask_sat_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/mask_sat_1.npy"
mask_ws_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/mask_ws_1.npy"

# Observed variables (observations)
observed_variables_sat:
  - "geopotential"
  - "temperature"
  - "u_component_of_wind"
  - "v_component_of_wind"
observed_variables_ws:
  - "10m_u_component_of_wind"
  - "10m_v_component_of_wind"
  - "2m_temperature"
  - "mean_sea_level_pressure"
  - "sea_surface_temperature"

# Covariance matrix of unnormalized observations
sigma_y_sat_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/covariance/satellite_all_variables.npy"
sigma_y_ws_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/covariance/weather_stations.npy"

# MMPS Solver
solver: !!str "bicgstab"
max_iter: !!int 2
tol: !!float 1e-8
warm_start: !!bool True