# Number of draws and samples
num_samples: !!int 512
num_draws: !!int 512

# Eval_target path
data_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/trajectories/2019_03_29_1.0_13_30.nc"
checkpoint_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/checkpoints/gencast_1deg.npz"

# Sample and output paths
conditional_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/PPC/all_variables/"
unconditional_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/PPC/unconditional/"
output_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/images/PPC/all_variables/atmospheric/v_component_of_wind/africa.svg"

# Variables
variables:
    - ["v_component_of_wind", 50]
    - ["v_component_of_wind", 250]
    - ["v_component_of_wind", 600]
    - ["v_component_of_wind", 1000]

# Standard deviations
stds:
    v_component_of_wind:
        50: !!float 0.3
        250: !!float 0.3
        600: !!float 0.3
        1000: !!float 0.3

# (Latitude, Longitude)
lat: !!int 8
lon: !!int 47

# Mask (observations)
mask_sat_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/mask_sat_1.npy"
mask_ws_path: !!str "/gpfs/home/acad/ulg-sysmod/tsavary/DataAssimilation/GenCast/data/observations/mask/mask_ws_1.npy"

# Labels
xlabels:
    - 'Level: 50 hPA'
    - 'Level: 250 hPA'
    - 'Level: 600 hPA'
    - 'Level: 1000 hPA'

# Colors
colors:
    - "red"
    - "blue"
    - "black"

# Titles
title: !!str Posterior Predictive Check (PPC) for V component of wind (atmospheric variable) at lat=8, lon=47 (Africa)

# Dimension of the plot
plot_size:
    num_row: !!int 2
    num_col: !!int 2
    width: !!float 12.
    height: !!float 8.
